<link rel="shortcut icon" href="./assets/img/functional/song.png" type="image/x-icon"/>
<link rel="stylesheet" href="./assets/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
<link rel="stylesheet" href="./assets/fonts/fontawesome-all.min.css">
<style>
    .userMenu {
        color: black;
    }
</style>
<div class="d-flex flex-column" id="content-wrapper">
        <div id="content">
            <nav class="navbar navbar-light navbar-expand bg-white shadow mb-4 topbar static-top">
                <div class="container-fluid">
                    <button class="btn btn-link d-md-none rounded-circle mr-3" id="sidebarToggleTop" type="button"><i
                                class="fas fa-bars"></i></button>
                    <ul class="nav navbar-nav flex-nowrap ml-auto">
                        <div class="d-none d-sm-block topbar-divider"></div>
                        <li class="nav-item dropdown no-arrow" role="presentation">
                            <div class="nav-item dropdown no-arrow"><a class="dropdown-toggle nav-link"
                                                                       data-toggle="dropdown" aria-expanded="false"
                                                                       href="#"><span
                                            class="d-none d-lg-inline mr-2 text-gray-600 small text-center">Wil je menu</span></a>
                                <div class="dropdown-menu shadow dropdown-menu-right animated--grow-in" role="menu">
                                    <a class="dropdown-item disabled userMenu" role="presentation" href="messages.php"><i
                                                class="fas fa-comments fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Berichten</a>
                                    <a class="dropdown-item userMenu" role="presentation" href="update-maker.php"><i
                                                class="fas fa-edit fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Updates</a>
                                    <a class="dropdown-item disabled userMenu" role="presentation" href="collection.php"><i
                                            class="fas fa-record-vinyl fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Onze collectie</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item userMenu" role="presentation" href="logout.php"><i
                                                class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Logout</a>
                                    <div class="dropdown-divider"></div>
                                    <p class="dropdown-item disabled userMenu" id="time-home"></p>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>