<?php
include 'config/config.php';
$getValue = mysqli_fetch_array($ConnectionLink->query("SELECT * FROM users WHERE USER_ID ='" . $_SESSION['id'] . "'"));

// Check if the user is logged in, if not then redirect him to login page
if (!isset($_SESSION["loggedin"]) || $_SESSION["loggedin"] !== true) {
header("location: login.php");
exit;
}
?>

<!DOCTYPE html>
<html lang="nl">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="shortcut icon" href="./assets/img/functional/song.png" type="image/x-icon"/>
    <title>Het Platenhuis - Admin - <?php echo $getValue['USER_FIRSTNAME']; ?></title>
    <link rel="stylesheet" href="./assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="./assets/fonts/fontawesome-all.min.css">
    <link rel="stylesheet" href="assets/css/custom.css">
    <script>
        function startTime() {
            let today = new Date();
            let h = today.getHours();
            let m = today.getMinutes();
            let s = today.getSeconds();
            let d = today.getDate();
            let mo = (today.getMonth() + 1);
            let y = today.getFullYear();
            m = checkTime(m);
            s = checkTime(s);
            document.getElementById('time-home').innerHTML =
                d + "/" + mo + "/" + y + "  " + h + ":" + m + ":" + s;
            let t = setTimeout(startTime, 500);
        }

        function checkTime(i) {
            if (i < 10) {
                i = "0" + i
            }
            return i;
        }
    </script>
</head>

<body id="page-top" onload="startTime()">
<div id="wrapper">
<nav class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0">
        <div class="container-fluid d-flex flex-column p-0">
            <a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="index.php">
                <div class="sidebar-brand-icon"><i class="fas fa-user-astronaut"></i></div>
                <div class="sidebar-brand-text mx-3"><span>Het Platenhuis</span></div>
            </a>
            <hr class="sidebar-divider my-0">
            <?php
            $activePage = basename($_SERVER['PHP_SELF'], ".php");
            ?>
            <ul class="nav navbar-nav text-light" id="accordionSidebar">
                <li class="nav-item" role="presentation"><a class="nav-link <?= ($activePage == 'index') ? 'active':''; ?>" href="./index.php"><i
                                class="fas fa-tachometer-alt"></i><span>Dashboard</span></a></li>

                <li class="nav-item" role="presentation"><a class="nav-link <?= ($activePage == 'songofday_page') ? 'active':''; ?>" href="./songofday_page.php">
                        <i class="fab fa-spotify"></i><span>Nummer van de Dag</span></a></li>

                <li class="nav-item" role="presentation"><a class="nav-link <?= ($activePage == 'update_page') ? 'active':''; ?>" href="./update_page.php"><i
                                class="far fa-edit"></i><span>Updates</span></a></li>

                <li class="nav-item" role="presentation"><a class="nav-link <?= ($activePage == 'current_admins_page') ? 'active':''; ?>" href="./current_admins_page.php"><i
                                class="fas fa-user"></i><span>Profielen</span></a></li>

                <li class="nav-item" role="presentation"><a class="nav-link <?= ($activePage == 'add_admin') ? 'active':''; ?>" href="./add_admin.php"><i
                                class="fas fa-user-edit"></i><span>Toevoegen</span></a></li>

                <li class="nav-item" role="presentation"><a class="nav-link disabled <?= ($activePage == 'inbox_page') ? 'active':''; ?>" href="./inbox_page.php"><i
                                class="fas fa-mail-bulk"></i><span>Inbox</span></a></li>

                <li class="nav-item" role="presentation"><a class="nav-link <?= ($activePage == 'add_new_mail') ? 'active':''; ?>" href="./add_new_mail.php"><i
                                class="fas fa-paper-plane"></i><span>Mail versturen</span></a></li>

                <li class="nav-item" role="presentation"><a class="nav-link disabled" href="#"><i
                                class="fas fa-tags"></i><span>Webshop</span></a></li>
                <?php
                $link = "./logout.php?USERNAME={$getValue['USERNAME']}"
                ?>
                <li class="nav-item" role="presentation"><a class="nav-link" href=<?php echo $link?>><i
                                class="far fa-user-circle"></i><span>Logout</span></a></li>

                <li class="nav-item" role="presentation"><a class="nav-link" href="https://hetplatenhuis.nl/"><i
                                class="fas fa-bars"></i><span>Naar de site</span></a></li>
            </ul>
            <div class="text-center d-none d-md-inline">
                <button class="btn rounded-circle border-0" id="sidebarToggle" type="button"></button>
            </div>
        </div>
    </nav>
<?php include '_layout-userlayout.phtml';