<footer class="bg-white sticky-footer">
    <div class="container my-auto">
        <div class="text-center my-auto copyright"><span>Copyright © 2020 bij <a href="https://hetplatenhuis.nl/">Het Platenhuis</a></span></div>
    </div>
</footer>
</div>
<a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a></div>
<script src="assets/js/jquery.min.js"></script>
<script src="assets/bootstrap/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
<script src="assets/js/theme.js"></script>
<!--<script>-->
<!--    (function(document){-->
<!--        var div = document.getElementById('container');-->
<!--        var icon = document.getElementById('icon');-->
<!--        var open = false;-->
<!---->
<!--        div.addEventListener('click', function(){-->
<!--            if(open){-->
<!--                icon.className = 'fa fa-arrow-down';-->
<!--            } else{-->
<!--                icon.className = 'fa fa-arrow-down open';-->
<!--            }-->
<!---->
<!--            open = !open;-->
<!--        });-->
<!--    })(document);-->
<!--</script>-->
</body>
</html>