<?php include_once 'config/config.php';
session_start();
$getValue = mysqli_fetch_array($ConnectionLink->query("SELECT * FROM users WHERE USER_ID ='" . $_SESSION['id'] . "'"));

?>

    <!DOCTYPE html>
    <html lang="nl">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <link rel="shortcut icon" href="./assets/img/functional/song.png" type="image/x-icon"/>
        <title>Het Platenhuis - Admin - <?php echo $getValue['USER_FIRSTNAME']; ?></title>
        <link rel="stylesheet" href="./assets/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet"
              href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
        <link rel="stylesheet" href="./assets/fonts/fontawesome-all.min.css">
        <link rel="stylesheet" href="assets/css/custom.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script>
            function startTime() {
                let today = new Date();
                let h = today.getHours();
                let m = today.getMinutes();
                let s = today.getSeconds();
                let d = today.getDate();
                let mo = (today.getMonth() + 1);
                let y = today.getFullYear();
                m = checkTime(m);
                s = checkTime(s);
                document.getElementById('time-home').innerHTML =
                    d + "/" + mo + "/" + y + "  " + h + ":" + m + ":" + s;
                let t = setTimeout(startTime, 500);
            }

            function checkTime(i) {
                if (i < 10) {
                    i = "0" + i
                }
                return i;
            }
        </script>
    </head>

<body id="page-top" onload="startTime()">
<div id="wrapper">
    <nav class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0">
        <div class="container-fluid d-flex flex-column p-0">
            <a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="#">
                <div class="sidebar-brand-icon"><i class="fas fa-user-astronaut"></i></div>
                <div class="sidebar-brand-text mx-3"><span>Het Platenhuis</span></div>
            </a>
            <hr class="sidebar-divider my-0">
            <ul class="nav navbar-nav text-light" id="accordionSidebar">
                <li class="nav-item" role="presentation"><a class="nav-link" href="./index.php"><i
                                class="fas fa-tachometer-alt"></i><span>Dashboard</span></a></li>

                <li class="nav-item dropdown show" role="presentation"><a class="nav-link dropdown-toggle" role="button" href="#" id="dropdownMenuMusic" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-music"></i><span>Muziek</span></a>
                    <div class="dropdown-menu mr-0" aria-labelledby="dropdownMenuMusic">
                        <h6 class="dropdown-header"><i class="fas fa-music"></i> Muziek</h6>
                        <a class="dropdown-item" href="./songofday_page.php">Nummer van de dag</a>
                        <a class="dropdown-item" href="./current_artists_page.php">Huidige artiesten</a>
                        <a class="dropdown-item" href="./add_artists.php">Artiest toevoegen</a>
                    </div>
                </li>

                <li class="nav-item dropdown show" role="presentation"><a class="nav-link dropdown-toggle" role="button" href="#" id="dropdownMenuMusic" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-users"></i><span>Profielen</span></a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuMusic">
                        <h6 class="dropdown-header"><i class="fas fa-users"></i> Profielen</h6>
                        <a class="dropdown-item" href="./current_admins_page.php">Gebruikers</a>
                        <a class="dropdown-item" href="./add_admin.php">Gebruiker toevoegen</a>
                    </div>
                </li>

                <li class="nav-item dropdown show" role="presentation"><a class="nav-link dropdown-toggle" role="button" href="#" id="dropdownMenuMusic" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-share-square"></i><span>Sociaal</span></a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuMusic">
                        <h6 class="dropdown-header"><i class="fas fa-share-square"></i> Sociaal</h6>
                        <a class="dropdown-item" href="./update_page.php">Updates</a>
                        <a class="dropdown-item" href="./add_new_mail.php">Mail</a>
                        <a class="dropdown-item disabled" href="#">Webshop</a>
                    </div>
                </li>
                <?php
                $link = "./logout.php?USERNAME={$getValue['USERNAME']}"
                ?>
                <li class="nav-item" role="presentation"><a class="nav-link" href=<?php echo $link?>><i
                                class="fas fa-sign-out-alt"></i><span>Logout</span></a></li>

                <li class="nav-item" role="presentation"><a class="nav-link" href="https://hetplatenhuis.nl/"><i
                                class="fas fa-bars"></i><span>Naar de site</span></a></li>
            </ul>
            <div class="text-center d-none d-md-inline">
                <button class="btn rounded-circle border-0" id="sidebarToggle" type="button"></button>
            </div>
        </div>
    </nav>
<?php include '_layout-userlayout.phtml';?>